openapi: 3.0.1
info:
  title: MZT Health Fitness App
  description: A webapp to assist a coach in managing their client's workout programs.
  version: 0.0.1
servers:
- url: /
paths:
  /customer/getCustomerById/{customerId}:
    get:
      description: Gets all customer information by customer ID
      operationId: getCustomerById
      parameters:
      - name: customerId
        in: path
        description: The customer id
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        200:
          description: OK Customer Info Obtained
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: Default
  /customer/getAllCustomers:
    get:
      description: Gets list of all customers
      operationId: getAllCustomers
      responses:
        200:
          description: OK Customer Info Obtained
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: Default
  /customer/measurements/{customerId}:
    get:
      description: Gets list of a customer's measurements by their id. This returns
        multiple measurements if there exists more than 1
      operationId: getCustomerMeasurementsById
      parameters:
      - name: customerId
        in: path
        description: The customer id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK Customer Measurement Obtained
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerMeasurement'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: Default
  /program/getProgramById/{programId}:
    get:
      description: Gets all program information by program ID
      operationId: getProgramById
      parameters:
      - name: programId
        in: path
        description: The program id
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        200:
          description: OK Program Info Obtained
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Program'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: Default
  /program/getAllPrograms:
    get:
      description: Gets list of all programs
      operationId: getAllPrograms
      responses:
        200:
          description: OK Program Info Obtained
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Program'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: Default
  /customer/measurements/:
    get:
      description: Gets list of a customer's measurements by their id and measurement
        date
      operationId: getCustomerMeasurementsByIdDate
      parameters:
      - name: customerId
        in: query
        description: The customer id
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      - name: measurementDate
        in: query
        description: The customer measurementDate
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: date
      responses:
        200:
          description: OK Customer Measurement Obtained
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerMeasurement'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: Default
  /exercise/getAllExercises:
    get:
      description: Gets list of all exercises
      operationId: getAllExercises
      responses:
        200:
          description: OK Exercise Info Obtained
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Exercise'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: Default
  /exercise/getExerciseById/{exerciseId}:
    get:
      description: Gets an exercise by ID
      operationId: getExerciseById
      parameters:
      - name: exerciseId
        in: path
        description: The exercise id
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        200:
          description: OK Exercise Info Obtained
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Exercise'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: Default
components:
  schemas:
    Customer:
      type: object
      properties:
        customerId:
          type: object
          readOnly: true
        firstName:
          type: string
        lastName:
          type: string
        signupDate:
          type: string
          format: date
        gender:
          type: string
        dob:
          type: string
          format: date
        activityLevel:
          type: string
        goal:
          type: string
        phone:
          type: string
        email:
          type: string
          format: email
        address1:
          type: string
        address2:
          type: string
        city:
          type: string
        zip:
          maximum: 99999
          minimum: 10000
          type: integer
          format: int64
        health_condition:
          type: string
        occupation:
          type: string
        availability:
          type: string
        commitment:
          type: string
      example:
        zip: 17207
        lastName: lastName
        signupDate: 2000-01-23
        goal: goal
        occupation: occupation
        gender: gender
        address2: address2
        city: city
        address1: address1
        commitment: commitment
        availability: availability
        health_condition: health_condition
        firstName: firstName
        phone: phone
        dob: 2000-01-23
        customerId: {}
        activityLevel: activityLevel
        email: ""
    CustomerMeasurement:
      type: object
      properties:
        customerId:
          type: object
          readOnly: true
        measurementDate:
          type: string
          format: date
        weight:
          type: number
          format: double
        height:
          type: number
          format: double
        bodyLeftArm:
          type: number
          format: double
        bodyRightArm:
          type: number
          format: double
        bodyLeftLeg:
          type: number
          format: double
        bodyRightLeg:
          type: number
          format: double
        bodyNeck:
          type: number
          format: double
        bodyHip:
          type: number
          format: double
        bodyRightLegThigh:
          type: number
          format: double
        bodyLeftLegThigh:
          type: number
          format: double
        dicksonMetric:
          type: number
          format: double
      example:
        bodyRightLeg: 2.3021358869347654518833223846741020679473876953125
        bodyRightLegThigh: 3.61607674925191080461672754609026014804840087890625
        bodyLeftArm: 1.46581298050294517310021547018550336360931396484375
        bodyHip: 9.301444243932575517419536481611430644989013671875
        weight: 0.80082819046101150206595775671303272247314453125
        measurementDate: 2000-01-23
        bodyLeftLeg: 5.63737665663332876420099637471139430999755859375
        dicksonMetric: 4.1456080298839363962315474054776132106781005859375
        bodyRightArm: 5.962133916683182377482808078639209270477294921875
        customerId: {}
        bodyNeck: 7.061401241503109105224211816675961017608642578125
        bodyLeftLegThigh: 2.027123023002321833274663731572218239307403564453125
        height: 6.02745618307040320615897144307382404804229736328125
    Exercise:
      type: object
      properties:
        exerciseId:
          type: object
        name:
          type: string
        description:
          type: string
        equipmentRequired:
          type: string
        exerciseType:
          type: string
        musclesTargeted:
          type: string
        setBreak:
          type: integer
          description: the time in seconds to rest between each set
        repetitions:
          type: integer
          description: the count of one atomic set of movement in a set
        sets:
          type: integer
          description: a set is composed of a number of repititions
        exerciseEstDuration:
          type: integer
          description: The time allocated to perform exercise
        exerciseTag:
          type: array
          items: {}
      example:
        exerciseId: {}
        sets: 1
        exerciseTag:
        - ""
        - ""
        exerciseType: exerciseType
        name: name
        exerciseEstDuration: 5
        description: description
        equipmentRequired: equipmentRequired
        setBreak: 0
        repetitions: 6
        musclesTargeted: musclesTargeted
    Program:
      type: object
      properties:
        programId:
          type: object
        title:
          type: string
        description:
          type: string
        programSDate:
          type: string
          format: date
        programEDate:
          type: string
          format: date
        coachId:
          type: object
      example:
        programId: {}
        title: title of program XXX
        description: description of program XXX
        programSDate: 2019-10-11
        programEDate: 2019-11-11
        coachId: {}
