openapi: 3.0.1
info:
  title: MZT Health Fitness App
  description: A webapp to assist a coach in managing their client's workout programs.
  version: 0.0.1
servers:
- url: /
paths:
  /customer/getCustomerById/{customer_id}:
    get:
      description: Gets all customer information by customer ID
      operationId: getCustomerById
      parameters:
      - name: customer_id
        in: path
        description: The customer id
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        200:
          description: OK Customer Info Obtained
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: customer.controller
  /customer/getAllCustomers:
    get:
      description: Gets list of all customers
      operationId: getAllCustomers
      responses:
        200:
          description: OK Customer Info Obtained
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: customer.controller
  /customer/measurements/{customer_id}:
    get:
      description: Gets list of a customer's measurements by their id. This returns
        multiple measurements if there exists more than 1
      operationId: getCustomerMeasurementsById
      parameters:
      - name: customer_id
        in: path
        description: The customer id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK Customer Measurement Obtained
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerMeasurement'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: customer.measurements.controller
  /customer/measurements/:
    get:
      description: Gets list of a customer's measurements by their id and measurement
        date
      operationId: getCustomerMeasurementsByIdDate
      parameters:
      - name: customer_id
        in: query
        description: The customer id
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      - name: measurementDate
        in: query
        description: The customer measurementDate
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: date
      responses:
        200:
          description: OK Customer Measurement Obtained
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerMeasurement'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: customer.measurements.controller
  /exercise/getAllExercises:
    get:
      description: Gets list of all exercises
      operationId: getAllExercises
      responses:
        200:
          description: OK Exercise Info Obtained
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Exercise'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: exercise.controller
  /exercise/getExerciseById/{exercise_id}:
    get:
      description: Gets an exercise by ID
      operationId: getExerciseById
      parameters:
      - name: exercise_id
        in: path
        description: The exercise id
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        200:
          description: OK Exercise Info Obtained
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Exercise'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: exercise.controller
  /exercise/addExercise:
    post:
      description: Creates new exercise
      operationId: addExercise
      requestBody:
        description: Add a new exercise
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Exercise'
      responses:
        200:
          description: OK Exercise Info Obtained
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exercise'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: exercise.controller
  /exercise/updateExercise:
    post:
      description: Updates an existing exercise
      operationId: updateExercise
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Exercise'
      responses:
        200:
          description: OK Exercise Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exercise'
                x-content-type: application/json
        400:
          description: 'Error: Bad Request'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: 'Error: Not Found'
      security:
      - basicAuth: []
      x-swagger-router-controller: exercise.controller
components:
  schemas:
    Customer:
      type: object
      properties:
        customer_id:
          type: object
          readOnly: true
        first_name:
          type: string
        last_name:
          type: string
        signup_date:
          type: string
          format: date
        gender:
          type: string
        dob:
          type: string
          format: date
        activity_level:
          type: string
        goal:
          type: string
        phone:
          type: string
        email:
          type: string
          format: email
        address1:
          type: string
        address2:
          type: string
        city:
          type: string
        zip:
          maximum: 99999
          minimum: 10000
          type: integer
          format: int64
        health_condition:
          type: string
        occupation:
          type: string
        availability:
          type: string
        commitment:
          type: string
      example:
        zip: 17207
        last_name: lastName
        signup_date: 2000-01-23
        goal: goal
        occupation: occupation
        gender: gender
        address2: address2
        city: city
        address1: address1
        commitment: commitment
        availability: availability
        health_condition: health_condition
        first_name: firstName
        phone: phone
        dob: 2000-01-23
        customer_id: {}
        activity_level: activityLevel
        email: ""
    CustomerMeasurement:
      type: object
      properties:
        customer_id:
          type: object
          readOnly: true
        measurement_date:
          type: string
          format: date
        weight:
          type: number
          format: double
        height:
          type: number
          format: double
        body_left_arm:
          type: number
          format: double
        body_right_arm:
          type: number
          format: double
        body_left_leg:
          type: number
          format: double
        body_right_leg:
          type: number
          format: double
        body_neck:
          type: number
          format: double
        body_hip:
          type: number
          format: double
        body_right_leg_thigh:
          type: number
          format: double
        body_left_leg_thigh:
          type: number
          format: double
        dickson_metric:
          type: number
          format: double
      example:
        body_right_leg: 2.3021358869347654518833223846741020679473876953125
        body_right_leg_thigh: 3.61607674925191080461672754609026014804840087890625
        body_left_arm: 1.46581298050294517310021547018550336360931396484375
        body_hip: 9.301444243932575517419536481611430644989013671875
        weight: 0.80082819046101150206595775671303272247314453125
        measurement_date: 2000-01-23
        body_left_leg: 5.63737665663332876420099637471139430999755859375
        dickson_metric: 4.1456080298839363962315474054776132106781005859375
        body_right_arm: 5.962133916683182377482808078639209270477294921875
        customer_id: {}
        body_neck: 7.061401241503109105224211816675961017608642578125
        body_left_leg_thigh: 2.027123023002321833274663731572218239307403564453125
        height: 6.02745618307040320615897144307382404804229736328125
    Exercise:
      type: object
      properties:
        exercise_id:
          type: object
        name:
          type: string
        description:
          type: string
        equipment_required:
          type: string
        exercise_type:
          type: string
        muscles_targeted:
          type: string
        set_break:
          type: integer
          description: the time in seconds to rest between each set
        repetitions:
          type: integer
          description: the count of one atomic set of movement in a set
        sets:
          type: integer
          description: a set is composed of a number of repititions
        exercise_es_duration:
          type: integer
          description: The time allocated to perform exercise
        exercise_tag:
          type: array
          items: {}
      example:
        exercis_id: {}
        sets: 1
        exercise_tag:
        - ""
        - ""
        exercise_type: exerciseType
        name: name
        exercise_est_duration: 5
        description: description
        equipment_required: equipmentRequired
        set_break: 0
        repetitions: 6
        muscles_targeted: musclesTargeted
